### ISSUE TITLE
求助：处理当前请求时发生了错误。

### ISSUE THREAD

**Issue by immoke** [721806280/feishu-notification-plugin#47]
您好，我安装了插件，然后在测试是提示报错：处理当前请求时发生了错误。Logging ID=f00f0b3b-493d-4908-8679-c2f29a784cdc。
从网关查询，也没有到open.feishu.cn的数据包，请问这个可能是什么原因呢？非常感谢。

Jenkins版本：2.413（最新）
Docker安装
CentOS 7
所有插件都已更新到最新。

再次感谢。

![image](https://github.com/721806280/feishu-notification-plugin/assets/18392319/fd942016-7ac4-4531-ad2f-5f84df0c1cf7)
![image](https://github.com/721806280/feishu-notification-plugin/assets/18392319/5bcbd96d-693d-44db-bca7-b39efa3ec8e1)
![image](https://github.com/721806280/feishu-notification-plugin/assets/18392319/46f86c96-cbae-4c7c-8f5e-9e8b255f99f9)

**Comment by 721806280** [comment]
重新安装一下插件，更新了[插件](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.1.0/feishu-notification.hpi)

**Comment by immoke** [comment]
您好，我重新安装了插件，还是这样的报错。网络上也还是没有新网络链接。

我尝试过：
1）直接重新depoy，还是报错；
2）将原来插件卸载，重新安装您链接的新插件，还是报错。

还有可能是什么问题，麻烦您帮忙看看， 谢谢。

**Comment by 721806280** [comment]
加Q 721806280
