### ISSUE TITLE
是否考虑添加二维码功能

### ISSUE THREAD

**Issue by views63** [721806280/feishu-notification-plugin#50]
增加一个输入内容自动生成二维码并上传飞书拿到 image_key以便在消息卡片中显示

**Comment by 721806280** [comment]
暂不考虑，因接口权限较高需申请，且需鉴权处理~  建议自行上传，插件中使用固定的image_key即可

**Comment by views63** [comment]
> 暂不考虑，因接口权限较高需申请，且需鉴权处理~ 建议自行上传，插件中使用固定的image_key即可

那如何在卡片信息中加入图片？
` feiShuTalk (
                        robot: "f72aa1bb-0f0b-47c7-8387-272d266dc25c",
                        type: "INTERACTIVE",
                        title: "📢 Jenkins 构建通知",
                        text: [
                            "📋 **任务名称**：[${JOB_NAME}](${JOB_URL})",
                            "🔢 **任务编号**：[${BUILD_DISPLAY_NAME}](${BUILD_URL})",
                            "🌟 **构建状态**: <font color='green'>成功</font>",
                            "🕐 **构建用时**: ${currentBuild.duration} ms",
                            "👤 **执  行 者**: Started by user anonymous",
                            "<at id=all></at>"
                        ],
                        buttons: [
                           [
                              title: "更改记录",
                              url: "${BUILD_URL}changes"
                           ],
                           [
                              title: "控制台",
                              type: "danger",
                              url: "${BUILD_URL}console"
                           ]
                        ]
                    )`

**Comment by 721806280** [comment]
> > 暂不考虑，因接口权限上方需申请，且需鉴权处理~建议自行上传，插件中使用固定的image_key即可
> 
> 那如何在响应信息中加入图片？使用` ![xxx](img_v2_fxxx)`无效
> 
> ```
>                         robot: "f72aa1bb-0f0b-47c7-8387-272d266dc25c",
>                         type: "INTERACTIVE",
>                         title: "📢 Jenkins 构建通知",
>                         text: [
>                             "📋 **任务名称**：[${JOB_NAME}](${JOB_URL})",
>                             "🔢 **任务编号**：[${BUILD_DISPLAY_NAME}](${BUILD_URL})",
>                             "🌟 **构建状态**: <font color='green'>成功</font>",
>                             "🕐 **构建用时**: ${currentBuild.duration} ms",
>                             "👤 **执  行 者**: Started by user anonymous",
>                             "<at id=all></at>"
>                         ],
>                         buttons: [
>                            [
>                               title: "更改记录",
>                               url: "${BUILD_URL}changes"
>                            ],
>                            [
>                               title: "控制台",
>                               type: "danger",
>                               url: "${BUILD_URL}console"
>                            ]
>                         ]
>                     )```
> ```

请重新安装插件，[配置参考](https://721806280.github.io/feishu-notification-plugin-doc/guide/front/pipeline.html#_6-img%E5%8D%A1%E7%89%87%E6%B6%88%E6%81%AF)

**Comment by peter100u** [comment]
请问Freestyle 项目如何配置imagekey呢
