### ISSUE TITLE
自定义消息 无法展示图片

### ISSUE THREAD

**Issue by peter100u** [721806280/feishu-notification-plugin#65]
[飞书插件]发送的消息详情: {"type":"INTERACTIVE","atOpenIds":[],"atAll":false,"title":"📢 ohla-android_official 成功","text":"📋 **任务名称**：[ohla-android_official](http://jenkins.ohlaapp.com/job/ohla-android_official/)\n🔢 **任务编号**：[#1591](http://jenkins.ohlaapp.com/job/ohla-android_official/1591/)\n🌟 **构建状态**:  <font color=green>成功</font>\n🕐 **构建用时**:  14 min\n👤 **执  行 者**:  peter\n* 环境：dev\n* 代码分支：origin/20230925迭代环境还原\n* 输出日志：false\n* 渠道：google\n* 安卓白包更新内容 👇🏻\n* 更新内容\n* 校验tapd上已解决的问题\n*  👇🏻\n* [安装包](https://www.pgyer.com/x21t)\n![二维码](https://www.xcxwo.com/app/qrcodeHistory/bae22db1df2ff30e0836cb7e09a21139d39c6c570fb620a9386810a94b612877)","buttons":[{"tag":"button","title":"更改记录","url":"http://jenkins.ohlaapp.com/job/ohla-android_official/1591//changes","type":"primary","text":{"tag":"plain_text","content":"更改记录"}},{"tag":"button","title":"控制台","url":"http://jenkins.ohlaapp.com/job/ohla-android_official/1591//console","type":"primary","text":{"tag":"plain_text","content":"控制台"}}],"at":{"atOpenIds":[],"isAtAll":false}}
Finished: SUCCESS

**Comment by 721806280** [comment]
@peter100u 替换为imgkey试试， 原因：飞书平台针对图片必须使用imgkey，无法解析https://www.xcxwo.com/app/qrcodeHistory/bae22db1df2ff30e0836cb7e09a21139d39c6c570fb620a9386810a94b612877

**Comment by peter100u** [comment]
> @peter100u 替换为imgkey试试， 原因：飞书平台针对图片必须使用imgkey，无法解析https://www.xcxwo.com/app/qrcodeHistory/bae22db1df2ff30e0836cb7e09a21139d39c6c570fb620a9386810a94b612877

那如何在自定义消息中，使用imagekey呢，有实例吗

**Comment by peter100u** [comment]
> > @peter100u 替换为imgkey试试， 原因：飞书平台针对图片必须使用imgkey，无法解析https://www.xcxwo.com/app/qrcodeHistory/bae22db1df2ff30e0836cb7e09a21139d39c6c570fb620a9386810a94b612877
> 
> 那如何在自定义消息中，使用imagekey呢，有实例吗

看到您的日志，自定义消息用的是text属性，内容是md字符串，里面如何把imagekey放进去呢， 官网说需要img类型，才可以识别imagekey作为图片解析

**Comment by 721806280** [comment]
> 的日志，自定义消息用的是text属性，内容是md字符串，里面如何把imagekey放进去呢， 官网说需要img类型，才可以识别imagekey作为图片解析

1.  先更新[插件](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.2.0/feishu-notification.hpi)
2. 自定义内容中加入图片，示例：`![hover_text](img_v2_16d4ea4f-6cd5-48fa-97fd-25c8d4e79b0g)`

**Comment by peter100u** [comment]
> > 的日志，自定义消息用的是text属性，内容是md字符串，里面如何把imagekey放进去呢， 官网说需要img类型，才可以识别imagekey作为图片解析
> 
> 1. 先更新[插件](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.2.0/feishu-notification.hpi)
> 2. 自定义内容中加入图片，示例：`![hover_text](img_v2_16d4ea4f-6cd5-48fa-97fd-25c8d4e79b0g)`

我测试看下,感谢

**Comment by peter100u** [comment]
是不是有延时， 最新版本还是1.0.0

**Comment by 721806280** [comment]
> 是不是有延时， 最新版本还是1.0.0

[1.2.0 ](https://github.com/721806280/feishu-notification-plugin/releases/tag/v1.2.0)
