### ISSUE TITLE
feature: 是否可以在发消息前，自行插入一段脚本

### ISSUE THREAD

**Issue by B1ackg0d** [721806280/feishu-notification-plugin#75]
大佬您好：
例如我希望在发消息前，动态对jenkins失败记录的文本进行提取，然后再发送消息。是否考虑支持这样的特性。能在发消息前插入一段脚本来实现。

**Comment by 721806280** [comment]
`
pipeline {
    agent any
    stages {
        stage('text'){
            steps {
                echo '发送文本消息...'
            }
            post {
                success {
                    feiShuTalk (
                        robot: 'f72aa1bb-0f0b-47c7-8387-272d266dc25c',
                        type: 'TEXT',
                        text: [
                            "新更新提醒",
                            '<at user_id="all">所有人</at>'
                        ]
                    )
                }
            }
        }
    }
}
`
例如在steps中操作？
