### ISSUE TITLE
求助：获取git commit message

### ISSUE THREAD

**Issue by META-KRIS** [721806280/feishu-notification-plugin#77]
目前使用的是 Freestyle 项目,
现在可以获取到git branchName,但git commit message 在环境变量里好像没有体现,
想问下如果获取git commit message呢

**Comment by 721806280** [comment]
本插件仅提供飞书消息通知相关功能，鉴于您的需求可参考Git相关的[插件](https://github.com/daniel-beck/changelog-environment-plugin)；
