### ISSUE TITLE
希望增加lark支持

### ISSUE THREAD

**Issue by peter100u** [721806280/feishu-notification-plugin#79]
希望也可以支持海外版本的lark, 毕竟他们是同一家API

**Comment by peter100u** [comment]
测试了下，修改了webhook，并无法发送

**Comment by 721806280** [comment]
***@***.*** ***@***.***>

**Comment by peter100u** [comment]
> > 测试了下，修改了webhook，并无法发送
> 
> @peter100u 因注册无法成功，无法测试，是否可以提供测试账号？加Q或邮箱：[721806280@qq.com](mailto:721806280@qq.com)
 已经加了

**Comment by 721806280** [comment]
[更新插件v1.2.1](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.2.1/feishu-notification.hpi)
