### ISSUE TITLE
个人资料页的手机号设置没有生效，无法实现构建完成后@发布者

### ISSUE THREAD

**Issue by boairy** [721806280/feishu-notification-plugin#82]
![20231213152441](https://github.com/721806280/feishu-notification-plugin/assets/28335726/35bef8aa-1c6a-453e-9992-0b6a9a7d3984)
这里目前填写手机号是没用的，由于飞书at人需要openid而不是手机号，我建议这里改为支持直接填写openid，消息context直接拼接就可以实现at发布人的功能

**Comment by 721806280** [comment]
@boairy 是的，在新版本中没有此项配置([尝试升级](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.2.1/feishu-notification.hpi))，@功能在机器人配置中配置即可;

**Comment by boairy** [comment]
配置中@等于写死配置，个人配置页是@提交人自己，不同的功能

**Comment by 721806280** [comment]
> 配置中@等于写死配置，个人配置页是@提交人自己，不同的功能

了解，下个版本加上～

**Comment by 721806280** [comment]
已支持请更新[插件](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.2.2/feishu-notification.hpi)后重试～
