### ISSUE TITLE
自定义消息支持消息卡片搭建平台生成的消息体

### ISSUE THREAD

**Issue by uliian** [721806280/feishu-notification-plugin#85]
需求：
1、我希望发送飞书卡片消息时候，能够定义header，如template字段，我希望在构建失败时发送红色标题的卡片。目前找不到定义
2、鉴于飞书机器人消息体的复杂性，能否开放一些更底层的消息body构造方式能够接受更多的body构造。而类型化的body构造用于便捷操作。

**Comment by 721806280** [comment]
> 需求： 1、我希望发送飞书卡片消息时候，能够定义header，如template字段，我希望在构建失败时发送红色标题的卡片。目前找不到定义 2、鉴于飞书机器人消息体的复杂性，能否开放一些更底层的消息body构造方式能够接受更多的body构造。而类型化的body构造用于便捷操作。

请更新[插件](https://github.com/721806280/feishu-notification-plugin/releases/download/v1.2.3/feishu-notification.hpi)后重试～
